apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ns-label-webhook
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ns-label-webhook
subjects:
- kind: ServiceAccount
  name: default
  namespace: webhook-system
roleRef:
  kind: ClusterRole
  name: ns-label-webhook
  apiGroup: rbac.authorization.k8s.io
