apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: ns-label-webhook
webhooks:
  - name: ns-labels.webhook.k8s
    admissionReviewVersions: ["v1"]
    sideEffects: None
    rules:
      - apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["deployments", "statefulsets", "daemonsets", "pods"]
        scope: "Namespaced"
    clientConfig:
      service:
        name: webhook
        namespace: default
        path: "/mutate"
      caBundle: Cg==  # Replace with the actual CA bundle
    timeoutSeconds: 3
    failurePolicy: Ignore
